"""add_entitlement_activated_at

Revision ID: 092806354b57
Revises: f7798efd5439
Create Date: 2024-12-11 14:34:34.273236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '092806354b57'
down_revision: Union[str, None] = 'f7798efd5439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entitlements', sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entitlements', 'activated_at')
    # ### end Alembic commands ###
