"""Add entitlement status

Revision ID: 90830ea1c796
Revises: 092806354b57
Create Date: 2024-12-18 13:07:14.943253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90830ea1c796'
down_revision: Union[str, None] = '092806354b57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('new', 'active', 'terminated', name='entitlementstatus').create(op.get_bind())
    op.add_column('entitlements', sa.Column('status', postgresql.ENUM('new', 'active', 'terminated', name='entitlementstatus', create_type=False), server_default='new', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entitlements', 'status')
    sa.Enum('new', 'active', 'terminated', name='entitlementstatus').drop(op.get_bind())
    # ### end Alembic commands ###
