"""create_entitlements

Revision ID: f7798efd5439
Revises: 
Create Date: 2024-12-11 13:22:26.882990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f7798efd5439'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entitlements',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('sponsor_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('sponsor_external_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('sponsor_container_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entitlements'))
    )
    op.create_index(op.f('ix_entitlements_id'), 'entitlements', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entitlements_id'), table_name='entitlements')
    op.drop_table('entitlements')
    # ### end Alembic commands ###
